name = "FPS++"
author = "Messi Inter Miami, FPS++ contributors"
version = "1.0.0+build.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a29f14dc309545a91a4602e52709bf31b847bab302e382821cde5ff3e3f0df3"

[versions]
fabric = "0.16.9"
minecraft = "1.16.5"
